name: Generate Snake

on:
  # Runs at 12:00 AM UTC every day
  schedule:
    - cron: "0 0 * * *"
  # Allows you to manually run the job from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: YOUR_GITHUB_USERNAME
          outputs: dist/github-contribution-grid-snake.svg

      - name: Add & Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Generated Snake Animation"
          git push

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
